import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { GetStaticProps, NextPage } from "next/types";
import { blogFeatureFlagEnabled } from "../../lib/edge-config";

type Props = {
  showBlogCard: boolean;
  serverDate: string;
};

export const getStaticProps: GetStaticProps = async () => {
  const showBlogCard = await blogFeatureFlagEnabled();

  const response = await fetch(
    "https://date-endpoint-to-be-deleted.vercel.app/api/timestamp"
  );
  const data = await response.json();

  return {
    props: {
      showBlogCard,
      serverDate: data.timestamp,
    },
    revalidate: 10,
  };
};

const Home: NextPage<Props> = ({ showBlogCard, serverDate }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.title}>Partner Demo - ISR</div>
          <p>
            <code className={styles.code}>{serverDate && `${serverDate}`}</code>
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
